# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AI Tennis Coach (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AI Tennis Coach (iOS)
  pod 'GoogleSignIn'
  pod 'Alamofire', '~> 5.5'

end

target 'AI Tennis Coach (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AI Tennis Coach (macOS)


end
