# For development only
# Compose automatically reads .env and allows you to use them like ${SO}

services:

  api:
    build: src/ # build image from Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:5000"
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432 # allows you to directly connect with psql instead of adminer

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  token-retriever:
    build: test/token_retriever/
    restart: unless-stopped
    ports:
      - "5000:80"
